# Font
# font_family      TX02NFMAAEOPSCPLMDIWEA
# bold_font        TX02NFMAAEOPSCPLMDIWEA
# italic_font      TX02NFMAAEOPSCPLMDIWEA
# bold_italic_font TX02NFMAAEOPSCPLMDIWEA
font_size        12.0

# Cursor
cursor_shape block
cursor_blink_interval 0

# Bell
# enable_audio_bell no
# visual_bell_duration 0

# Window
background_opacity 0.8
background_blur 64
background #1e1e1e
foreground #e0e0e0

# Window size
remember_window_size no
initial_window_width  120c
initial_window_height 40c

# Padding (in pts)
window_padding_width 0 6 6 6

# Tabs
tab_bar_edge            top
tab_bar_style           powerline
tab_powerline_style     angled
tab_title_template      " {index}: {title} "
active_tab_foreground   #1e1e1e
active_tab_background   #e0e0e0
active_tab_font_style   bold
inactive_tab_foreground #888888
inactive_tab_background #333333
inactive_tab_font_style normal
tab_bar_background      #1e1e1e

map ctrl+shift+t new_tab_with_cwd

# macOS specific
macos_option_as_alt yes
macos_titlebar_color background


# BEGIN_KITTY_FONTS
font_family      family="TX-02"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
