# Font
font_family      TX02NFMAAEOPSCPLMDIWEA
bold_font        TX02NFMAAEOPSCPLMDIWEA
italic_font      TX02NFMAAEOPSCPLMDIWEA
bold_italic_font TX02NFMAAEOPSCPLMDIWEA
font_size        12.0

# Cursor
cursor_shape block
cursor_blink_interval 0

# Bell
enable_audio_bell no
visual_bell_duration 0

# Window
background_opacity 0.8
background_blur 64
background #1e1e1e
foreground #e0e0e0

# Window size (120 columns x 30 rows to match Terminal.app)
remember_window_size no
initial_window_width  120c
initial_window_height 40c

# Tabs
tab_bar_edge            top
tab_bar_style           powerline
tab_powerline_style     angled
tab_title_template      " {index}: {title} "
active_tab_foreground   #1e1e1e
active_tab_background   #e0e0e0
active_tab_font_style   bold
inactive_tab_foreground #888888
inactive_tab_background #333333
inactive_tab_font_style normal
tab_bar_background      #1e1e1e

# macOS specific
macos_option_as_alt yes
macos_titlebar_color background
