require("gabe.config.lazy")
require("gabe.config.coc")
require("gabe.config.bufferline")
require("gabe.config.nvim-ufo")
require("gabe.config.nvim-cursorline")
require("gabe.config.lualine")
require("gabe.config.conform")
require("gabe.config.sunglasses")
require("gabe.config.neo-tree")
require("gabe")
vim.cmd.colorscheme("kanagawa-dragon")
vim.cmd("Neotree show")
